parameters:
    # Default XSL stylesheets for XmlText rendering to HTML5.
    # Built-in stylesheets are treated as custom for the sake of extensibility.
    ibexa.site_access.config.default.fieldtypes.ezxml.custom_xsl:
        -
            path: "%kernel.project_dir%/vendor/netgen/ibexa-xmltext-fieldtype/lib/FieldType/XmlText/Input/Resources/stylesheets/eZXml2Html5_core.xsl"
            priority: 0
        -
            path: "%kernel.project_dir%/vendor/netgen/ibexa-xmltext-fieldtype/lib/FieldType/XmlText/Input/Resources/stylesheets/eZXml2Html5_custom.xsl"
            priority: 0
