services:
    ezpublish_rest.field_type_processor.ezxmltext:
        class: eZ\Publish\Core\REST\Common\FieldTypeProcessor\XmlTextProcessor
        tags:
            - { name: ibexa.rest.field_type.processor, alias: ezxmltext }

    ezxmltext.persistence.legacy.content_model_gateway:
        class: eZ\Publish\Core\FieldType\XmlText\Persistence\Legacy\ContentModelGateway
        arguments:
            - "@ibexa.persistence.connection"

    ezxmltext.command.convert_to_richtext:
        class: EzSystems\EzPlatformXmlTextFieldTypeBundle\Command\ConvertXmlTextToRichTextCommand
        arguments:
            - "@ibexa.api.repository"
            - "@ezxmltext.persistence.legacy.content_model_gateway"
            - "@ezxmltext.richtext_converter"
            - "%kernel.cache_dir%"
            - "@?logger"
        tags:
            -  { name: console.command, command: ezxmltext:convert-to-richtext }

    ezxmltext.command.convert_to_richtext_sub_process:
        class: EzSystems\EzPlatformXmlTextFieldTypeBundle\Command\ConvertXmlTextToRichTextCommandSubProcess
        parent: ezxmltext.command.convert_to_richtext
        tags:
            -  { name: console.command, command: ezxmltext:convert-to-richtext-sub-process }

    ezxmltext.command.import_xml:
        class: EzSystems\EzPlatformXmlTextFieldTypeBundle\Command\ImportXmlCommand
        arguments:
            - "@ezxmltext.persistence.legacy.content_model_gateway"
            - "@ezxmltext.richtext_converter"
        tags:
            -  { name: console.command, command: ezxmltext:import-xml }

    ezxmltext.richtext_converter:
        class: eZ\Publish\Core\FieldType\XmlText\Converter\RichText
        arguments:
            - "@ibexa.api.repository"
            - "@?logger"
            - "@ibexa.richtext.validator.docbook"
